spring:
    application:
        name: jtw-back
    datasource:
        url: jdbc:mariadb://222.234.132.247:3306/jdg
        username: root
        password: 1234
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database-platform: org.hibernate.dialect.MariaDBDialect

server:
    port: 8081
    servlet:
        context-path: /api

mybatis:
    config-location: classpath:mybatis-config.xml
    mapper-locations: classpath:mapper/*.xml


logging:
    level:
        org.mybatis: DEBUG
        org.apache.ibatis: DEBUG
        jdbc.sqlonly: off
        jdbc.sqltiming: info
        jdbc.resultsettable: info
        jdbc.audit: off
        jdbc.resultset: off
        jdbc.connection: off